FROM python:3.10-slim

COPY requirements.txt /app/requirements.txt
COPY ./data/ /app/data/
COPY ./producer.py /app/producer.py

WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python3", "producer.py"]
