include:
  - infra.yaml

services:
  producer:
    build:
      context: producer/
      dockerfile: dockerfile
    depends_on:
      - broker-1
      - broker-2
    networks:
      - kafka

networks:
  kafka:
    name: kafka