include:
  - infra.yaml

services:
  producer:
    container_name: producer
    build:
      context: producer/
      dockerfile: dockerfile
    depends_on:
      - broker-1
      - broker-2
    networks:
      - kafka

  consumer-1:
    container_name: consumer-1
    build:
      context: consumer/
      dockerfile: dockerfile
    environment:
      - TOPIC=Topic1
      - MINIO_BUCKET=transportation-bucket-1
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD:-minioadmin}
    depends_on:
      - broker-1
      - broker-2
      - minio
    networks:
      - kafka

  consumer-2:
    container_name: consumer-2
    build:
      context: consumer/
      dockerfile: dockerfile
    environment:
      - TOPIC=Topic2
      - MINIO_BUCKET=transportation-bucket-2
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD:-minioadmin}
    depends_on:
      - broker-1
      - broker-2
      - minio
    networks:
      - kafka
    
networks:
  kafka:
    name: kafka